# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
fMatProd <- function(x, y) {
    .Call('_rmkl_fMatProd', PACKAGE = 'rmkl', x, y)
}

#' @export
fMatSolve <- function(x, y) {
    .Call('_rmkl_fMatSolve', PACKAGE = 'rmkl', x, y)
}

#' @export
fMatInv <- function(x) {
    .Call('_rmkl_fMatInv', PACKAGE = 'rmkl', x)
}

#' Function to get the version of Intel MKL
#'
#' @return The version of Intel MKL
#' @examples
#' getMKLVersion()
#' @export
getMKLVersion <- function() {
    .Call('_rmkl_getMKLVersion', PACKAGE = 'rmkl')
}

#' Function to get/set the number of threads used in Intel MKL
#'
#' @param nThreads The number of threads you want to use in Intel MKL.
#' @return The number of threads.
#'
#' @examples
#' \dontrun{
#' getMKLThreads() # Default is the number of cores your CPU has
#' setMKLThreads(1)
#' getMKLThreads() # 1
#' }
#' @name mkl_threads
#' @export
setMKLThreads <- function(nThreads) {
    .Call('_rmkl_setMKLThreads', PACKAGE = 'rmkl', nThreads)
}

#' @name mkl_threads
#' @export
getMKLThreads <- function() {
    .Call('_rmkl_getMKLThreads', PACKAGE = 'rmkl')
}

